name: Hourly Tech Tweet Scraper
on:
    schedule:
        # Adjusted to fit indian time (IST = UTC + 5:30).
         # Format: minute hour day month weekday
        - cron: '30 4,6,8,10,12,14,16,18 * * *' # This will run at 10AM, 12PM, 2PM, 4PM, 6PM, 8PM, 10PM, and 12AM IST every day.
    workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

concurrency:
    group: twitter-telegram-bot
    cancel-in-progress: false

jobs:
    scrape-and-send:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Run Bot Script
              env:
                  APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
                  APIFY_ACTOR_ID: ${{ secrets.APIFY_ACTOR_ID }}
                  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
                  NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
              run: npm run bot
